### PR TITLE
Support screenIdle as Mac FeatureState

### PR DESCRIPTION
**Pull request by erichs**
Work in progress toward supporting an idle lock timeout security setting (#67).

This is a bit of a hack, as this is really more of a "NumericSetting"
validation, which doesn't exist yet. "OFF" and "ON" security states don't really apply here, but the logic does validate correctly.

screen shot 2018-09-21 at 12 39 53 pm

### CODE REVIEW

**Comment by erichs** [comment]
Feedback welcome! Ideally, I'd like to see some kind of integer `FeatureSetting` type or something that made the numeric policy setting available to the Handlebars templates when rendering instructions, and perhaps display the raw system setting in the `device[security]` response, instead of a misleading value like `"screenIdle": "OFF"`, which is what this implementation currently displays.

**Comment by erichs** [comment]
Thanks, @rmcvey. I'm curious what your thoughts are for handling this type of control. It's clearly a numeric value, and not a boolean feature toggle, but how should this be displayed and made configurable via policy?

One thought that did occur to me is that `semver.coerce` actually works OK for strings representing integer values (coerces to "version" `<int>.0.0`). This would allow for osVersion-like policy configuration like:

**Comment by rmcvey** [comment]
I've (finally) finished a first pass review of this PR. Code looks good and I like the Numeric type, however I do have a couple issues:
- Our team would really like to stay away from asking regular users to execute terminal commands, are there any UIs that can be used to control this value instead?
- It seems like the command doesn't work in Mojave, am I missing something?
```
rmcvey@MacBook-Pro: (master *) /var/www/stethoscope/app
$ sudo defaults -currentHost write com.apple.screensaver idleTime 120
rmcvey@MacBook-Pro: (master *) /var/www/stethoscope/app
$ osqueryi --json 'select * from preferences where domain = "com.apple.screensaver" and key = "idleTime";' | jq
[]
```

**Comment by erichs** [comment]
Thanks, @rmcvey! I agree, it is more user-friendly to provide UI options for remediation. I'll update the instructions to navigate to: Preferences -> Desktop & Screen Saver -> Screen Saver tab, start after dropdown:

screen shot 2018-10-24 at 5 00 13 pm

Apple has made configuring/remediating screensaver security quite difficult in recent releases: https://blog.kolide.com/screensaver-security-on-macos-10-13-is-broken-a385726e2ae2

I'm not actually surprised this doesn't work in Mojave. I'm curious, does Mojave still preserve the above UI path?

**Comment by erichs** [comment]
How do you feel about the syntax for `<=`, `>=`, `<`, `>` -type comparison operators for numeric controls in policy?

**Comment by erichs** [comment]
Rebased against 2.1.0 release. This is a pass at implementing a new GraphQL scalar type, NumericRange, that accepts numeric (ints, floats) strings or "semver" like formatted range strings, and returns PASS/FAIL if the control satisfies the NumericRange.

**Comment by rmcvey** [comment]
Hey @erichs, that UI path still works in Mojave - this is definitely a more accessible set of instructions.

I think the `NumericRange` type looks great. I'll pull down the latest version and run through some checks but I think this is looking good to merge.

Question: is line 193 supposed to be there? https://github.com/Netflix-Skunkworks/stethoscope-app/pull/67/commits/9ff736f02d7d9aa0cb176febab3eaed4260ae7d8#diff-03b02e4865819617ab2426b993b02d1fR193

**Comment by erichs** [comment]
Good catch! fixed.

**Comment by rmcvey** [comment]
Ok, two last (minor) changes and we are good to go. We can deep link to the screen saver screen using `/System/Library/PreferencePanes/DesktopScreenEffectsPrefs.prefPane`.

If you could modify your instructions to:

```diff
-1. Click the Screen Saver tab.
+1. Click the [Screen Saver](open:///System/Library/PreferencePanes/DesktopScreenEffectsPref.prefPane) tab.
```

And add this protocol handler in `src/lib/protocolHandlers.js`:

```javascript
protocol.registerHttpProtocol('open', (request, cb) => {
  shell.openItem(request.url.replace('open://', ''))
})
```

We are good to go.

**Comment by erichs** [comment]
Nice! I didn't know that mechanism even existed.

**Comment by rmcvey** [comment]
Perfect, thanks so much for your contribution @erichs!

**Pull request merged**
